#eureka: 
#  client:       
#    registerWithEureka: true   
#    fetchRegistry: true
#    service-url: 
#      defaultZone: http://nodeA:10001/eureka/
#      #defaultZone: http://nodeA:10001/eureka/,http://nodeB:10002/eureka/
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
#      config:
#        server-addr: 127.0.0.1:8848